#!/usr/bin/env bash
# pilot-ledger.sh --retention-root <retention_root> --record --scenario <id>
#                  --rep <n> --operator <identity> --checklist <checklist.json>
# pilot-ledger.sh --retention-root <retention_root> --verify [--family <f>]
#
# T-E40-F10-006 (spec.md REQ-F-005, ADR-F10-09): the offline pilot-inspection
# attestation ledger. `--record` appends one operator attestation per
# scenario family into <retention_root>/pilot-ledger.jsonl, capturing the
# inspected run reference, the checklist item results, the inspecting
# operator identity, and the digests of the retained artifacts inspected.
# `--verify` re-computes those same digests from the artifacts CURRENTLY
# retained on disk and reports per-family pass/fail.
#
# ADR-F10-09: the gate is an artifact-digest attestation, not a boolean
# flag or a bare run-id reference -- either of those would be unable to
# detect a later change to the retained evidence. `--verify` therefore
# never trusts a stored digest without recomputing it fresh.
#
# Digest computation (bench/reports/lifecycle-baseline-schema.yaml
# digest_rules, matching I-05/I-07/I-08's own digest_rules blocks):
# algorithm sha256, lowercase hex encoding. A single file is digested as
# `file_encoding: sha256_raw_bytes` (raw bytes, no re-serialization). A
# directory (evidence/, transcripts/) is digested as a `canonicalization:
# compact_json_sorted_keys_utf8` document: the sorted list of
# {relative_path, sha256_raw_bytes} for every file it contains, sha256'd.
#
# The eight artifacts digested per (scenario, rep) are exactly
# bench/reports/lifecycle-baseline-schema.yaml's `retention_required_
# artifacts` list (spec.md Data model changes): package.yaml, evidence,
# transcripts, entity-history.json, lifecycle.jsonl, evaluation.jsonl,
# oracle.json, manifest.json.
#
# Ledger row fields match the schema's `pilot_attestation_required_fields`:
# /run_reference, /checklist_results, /operator_identity,
# /inspected_artifact_digests (plus this script's own `family` and
# `recorded_at` bookkeeping fields, which the schema does not forbid).
#
# `--verify` groups the (append-only) ledger by family and uses the LATEST
# row recorded for each family -- a re-attestation supersedes an earlier
# one, it does not need to be deleted. Verifying a family absent from the
# ledger fails with `no_attestation`; verifying a family whose recorded
# digests no longer match the current retained bytes fails with
# `stale_digest` (naming the artifact(s) that changed) -- this is also
# what catches a `--reclaim-incomplete`-quarantined-and-rerun pair: the
# regenerated bytes at the same retention path simply recompute to a
# different digest, with no special-case code required.
#
# Exit status: 0 record success / verify all-requested-families pass,
# 1 verify found at least one failing family, 2 usage error.
set -euo pipefail

usage() {
	cat >&2 <<'EOF'
usage: pilot-ledger.sh --retention-root <retention_root> --record \
         --scenario <id> --rep <n> --operator <identity> \
         --checklist <checklist.json>
       pilot-ledger.sh --retention-root <retention_root> --verify [--family <f>]
EOF
	exit 2
}

retention_root=""
action=""
scenario=""
rep=""
operator=""
checklist=""
family=""

while [[ $# -gt 0 ]]; do
	case "$1" in
	--retention-root)
		[[ $# -ge 2 ]] || usage
		retention_root="$2"
		shift 2
		;;
	--record)
		[[ -z "$action" ]] || usage
		action="record"
		shift
		;;
	--verify)
		[[ -z "$action" ]] || usage
		action="verify"
		shift
		;;
	--scenario)
		[[ $# -ge 2 ]] || usage
		scenario="$2"
		shift 2
		;;
	--rep)
		[[ $# -ge 2 ]] || usage
		rep="$2"
		shift 2
		;;
	--operator)
		[[ $# -ge 2 ]] || usage
		operator="$2"
		shift 2
		;;
	--checklist)
		[[ $# -ge 2 ]] || usage
		checklist="$2"
		shift 2
		;;
	--family)
		[[ $# -ge 2 ]] || usage
		family="$2"
		shift 2
		;;
	--help)
		usage
		;;
	*)
		usage
		;;
	esac
done

[[ -n "$retention_root" ]] || usage
[[ -n "$action" ]] || usage

command -v python3 >/dev/null 2>&1 || {
	echo "pilot-ledger: python3 not found on PATH" >&2
	exit 2
}

[[ -d "$retention_root" ]] || {
	echo "pilot-ledger: retention root not found: $retention_root" >&2
	exit 2
}
RETENTION_ROOT_CANON="$(cd "$retention_root" && pwd)"
LEDGER_PATH="$RETENTION_ROOT_CANON/pilot-ledger.jsonl"

# T-E40-F10-006 rework (code-review-2026-08-20T1731-E40-F10.md finding 13):
# assert_within_out_root is the SAME containment guard run-lifecycle-batch.sh
# and run-review-comparison.sh already use for their own retention paths
# (bench/scripts/lib/path-safety.sh). Its caller contract requires
# out_root_canon to be set via `realpath -m` (not the `cd && pwd` form used
# for RETENTION_ROOT_CANON above, which can preserve a symlink component) --
# followed here exactly so the two canonicalizations can never disagree.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
out_root_canon="$(realpath -m -- "$RETENTION_ROOT_CANON")"
# shellcheck source=lib/path-safety.sh
source "$SCRIPT_DIR/lib/path-safety.sh"

# REQ-F-002's scenario_id grammar (bench/scenarios/packages/<scenario_id>/
# package.yaml identity block: "unique lowercase-kebab identity"), the same
# closed grammar the I-04 scenario contract test (tests/contracts,
# e40I04ScenarioIDPattern) enforces for I-04 admission. --scenario is interpolated
# into a retention-relative path below; validating it against this grammar
# up front means it can never contain '/', '.', or an absolute-path prefix,
# so a traversal escape is structurally impossible before any file is
# touched.
SCENARIO_ID_GRAMMAR='^[a-z0-9]+(-[a-z0-9]+)*$'

case "$action" in
record)
	[[ -n "$scenario" ]] || usage
	[[ "$scenario" =~ $SCENARIO_ID_GRAMMAR ]] || {
		echo "pilot-ledger: --scenario must be a lowercase-kebab scenario_id (REQ-F-002 grammar: ^[a-z0-9]+(-[a-z0-9]+)*\$), got '$scenario'" >&2
		exit 2
	}
	[[ -n "$rep" ]] || usage
	[[ "$rep" =~ ^[0-9]+$ ]] || {
		echo "pilot-ledger: --rep must be a non-negative integer, got '$rep'" >&2
		exit 2
	}
	[[ -n "$operator" ]] || usage
	[[ -n "$checklist" ]] || usage
	[[ -f "$checklist" ]] || {
		echo "pilot-ledger: checklist file not found: $checklist" >&2
		exit 2
	}

	# Containment check on the constructed retention-relative path, BEFORE
	# any read or write against it -- defense in depth alongside the
	# grammar check above (finding 13's fix instruction: validate the
	# grammar AND containment-check the constructed path, exactly as
	# run-lifecycle-batch.sh/run-review-comparison.sh already do for their
	# own retention paths).
	scenario_dir_precheck="$RETENTION_ROOT_CANON/scenarios/$scenario/$rep"
	assert_within_out_root "$scenario_dir_precheck" || exit 2

	python3 - "$RETENTION_ROOT_CANON" "$scenario" "$rep" "$operator" "$checklist" "$LEDGER_PATH" <<'PYEOF'
import hashlib
import json
import os
import sys
import time

try:
    import yaml
except ImportError:
    print("pilot-ledger: PyYAML not available", file=sys.stderr)
    raise SystemExit(2)

retention_root, scenario_id, rep_str, operator, checklist_path, ledger_path = sys.argv[1:7]
rep = int(rep_str)

# The eight canonical retained artifacts (bench/reports/
# lifecycle-baseline-schema.yaml retention_required_artifacts).
RETAINED_ARTIFACTS = [
    "package.yaml", "evidence", "transcripts", "entity-history.json",
    "lifecycle.jsonl", "evaluation.jsonl", "oracle.json", "manifest.json",
]


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def digest_of_path(path):
    # file_encoding: sha256_raw_bytes for a single file; a directory is
    # digested as canonicalization: compact_json_sorted_keys_utf8 over the
    # sorted {path, sha256} list of every file it contains -- both under
    # the shared digest_rules algorithm/encoding (sha256, lowercase hex).
    #
    # code-review-2026-08-20T1731-E40-F10.md finding 3: an empty directory
    # (os.walk() yields zero files) previously still produced a real,
    # non-None digest -- sha256 of the canonicalized empty list `[]` -- so
    # a required directory artifact (evidence/, transcripts/) that was
    # never actually populated satisfied the `digest is None` missing-check
    # below. A directory with zero files is therefore treated exactly like
    # a directory that doesn't exist: both return None. This mirrors
    # run-lifecycle-batch.sh's own retain_pair() fix (commit 759fd7c9),
    # which stopped treating an unconditionally-empty mkdir as real
    # content.
    if os.path.isdir(path):
        entries = []
        for root, dirs, files in os.walk(path):
            dirs.sort()
            for fname in sorted(files):
                fpath = os.path.join(root, fname)
                relpath = os.path.relpath(fpath, path).replace(os.sep, "/")
                with open(fpath, "rb") as fh:
                    entries.append({"path": relpath, "sha256": sha256_bytes(fh.read())})
        if not entries:
            return None
        entries.sort(key=lambda e: e["path"])
        canonical = json.dumps(entries, sort_keys=True, separators=(",", ":")).encode("utf-8")
        return sha256_bytes(canonical)
    if os.path.isfile(path):
        with open(path, "rb") as fh:
            return sha256_bytes(fh.read())
    return None


# T-E40-F10-006 rework finding 13: --scenario is already validated against
# REQ-F-002's lowercase-kebab grammar and containment-checked by the caller
# (assert_within_out_root) before this subprocess is even started -- both
# BEFORE any read or write, per the finding's fix instruction. This
# realpath-based re-check is belt-and-suspenders against this exact
# subprocess someday being invoked directly with an unvalidated argv,
# independent of the bash-side guard.
RETENTION_ROOT_REAL = os.path.realpath(retention_root)


def within_retention_root(path):
    real = os.path.realpath(path)
    return real == RETENTION_ROOT_REAL or real.startswith(RETENTION_ROOT_REAL + os.sep)


scenario_dir = os.path.join(retention_root, "scenarios", scenario_id, str(rep))
if not within_retention_root(scenario_dir):
    print(f"pilot-ledger: refusing --scenario '{scenario_id}': resolves outside retention root", file=sys.stderr)
    raise SystemExit(2)
if not os.path.isdir(scenario_dir):
    print(f"pilot-ledger: no retained scenario directory found: {scenario_dir}", file=sys.stderr)
    raise SystemExit(2)

package_path = os.path.join(scenario_dir, "package.yaml")
if not os.path.isfile(package_path):
    print(f"pilot-ledger: package.yaml missing under {scenario_dir}", file=sys.stderr)
    raise SystemExit(2)
with open(package_path) as f:
    pkg = yaml.safe_load(f) or {}
family = str(pkg.get("entity_family") or "")
if not family:
    print(f"pilot-ledger: {package_path} has no entity_family; cannot determine scenario family", file=sys.stderr)
    raise SystemExit(2)

digests = {}
missing = []
for name in RETAINED_ARTIFACTS:
    digest = digest_of_path(os.path.join(scenario_dir, name))
    if digest is None:
        missing.append(name)
    digests[name] = digest
if missing:
    print(
        f"pilot-ledger: cannot record attestation, missing retained artifact(s) under {scenario_dir}: {', '.join(missing)}",
        file=sys.stderr,
    )
    raise SystemExit(2)

with open(checklist_path) as f:
    checklist_results = json.load(f)

record = {
    "family": family,
    "run_reference": {
        "scenario_id": scenario_id,
        "rep": rep,
        "retention_path": f"scenarios/{scenario_id}/{rep}",
    },
    "operator_identity": operator,
    "checklist_results": checklist_results,
    "inspected_artifact_digests": digests,
    "recorded_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
}
with open(ledger_path, "a", encoding="utf-8") as f:
    f.write(json.dumps(record, sort_keys=True) + "\n")

print(f"pilot-ledger: recorded attestation for family '{family}' (scenario_id={scenario_id}, rep={rep})")
PYEOF
	exit $?
	;;
verify)
	python3 - "$RETENTION_ROOT_CANON" "$LEDGER_PATH" "$family" <<'PYEOF'
import hashlib
import json
import os
import re
import sys

retention_root, ledger_path, family_filter = sys.argv[1:4]

RETAINED_ARTIFACTS = [
    "package.yaml", "evidence", "transcripts", "entity-history.json",
    "lifecycle.jsonl", "evaluation.jsonl", "oracle.json", "manifest.json",
]

# REQ-F-002 lowercase-kebab scenario_id grammar -- the same closed grammar
# --record validates argv against and the I-04 scenario contract test
# (tests/contracts, e40I04ScenarioIDPattern) enforces for I-04 admission.
# Applied here too because
# `ref.get("scenario_id")` below comes from the (append-only, hand-editable)
# ledger file, not a freshly-validated argv -- a row written before this fix
# landed, or a hand-edited ledger, could still carry an unsafe value.
SCENARIO_ID_PATTERN = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")

RETENTION_ROOT_REAL = os.path.realpath(retention_root)


def within_retention_root(path):
    real = os.path.realpath(path)
    return real == RETENTION_ROOT_REAL or real.startswith(RETENTION_ROOT_REAL + os.sep)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def digest_of_path(path):
    # code-review-2026-08-20T1731-E40-F10.md finding 3: an empty directory
    # must be treated as missing, exactly like --record's digest_of_path
    # (see that heredoc's comment) -- otherwise a required directory
    # artifact that lost its content after attestation (or was never
    # populated because a pre-fix --record recorded it empty) would compare
    # None == None and be silently reported "verified" instead of stale.
    if os.path.isdir(path):
        entries = []
        for root, dirs, files in os.walk(path):
            dirs.sort()
            for fname in sorted(files):
                fpath = os.path.join(root, fname)
                relpath = os.path.relpath(fpath, path).replace(os.sep, "/")
                with open(fpath, "rb") as fh:
                    entries.append({"path": relpath, "sha256": sha256_bytes(fh.read())})
        if not entries:
            return None
        entries.sort(key=lambda e: e["path"])
        canonical = json.dumps(entries, sort_keys=True, separators=(",", ":")).encode("utf-8")
        return sha256_bytes(canonical)
    if os.path.isfile(path):
        with open(path, "rb") as fh:
            return sha256_bytes(fh.read())
    return None


# Group by family; an append-only ledger's LATEST row per family is the
# current attestation -- a re-record supersedes an earlier one.
latest_by_family = {}
if os.path.isfile(ledger_path):
    with open(ledger_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                continue
            fam = entry.get("family")
            if fam:
                latest_by_family[fam] = entry

targets = [family_filter] if family_filter else sorted(latest_by_family.keys())

any_fail = False
for fam in targets:
    entry = latest_by_family.get(fam)
    if entry is None:
        print(f"family={fam}: FAILED (no_attestation)")
        any_fail = True
        continue
    ref = entry.get("run_reference") or {}
    scenario_id = ref.get("scenario_id")
    rep = ref.get("rep")
    # Finding 13's fix, applied on the read side: validate the grammar AND
    # containment-check the constructed path BEFORE any read, exactly as
    # --record now does -- a ledger row is data, not a trusted argv, so a
    # malformed/unsafe scenario_id here must fail the family's verification
    # rather than being dereferenced.
    if (
        not isinstance(scenario_id, str)
        or not SCENARIO_ID_PATTERN.match(scenario_id)
        or not isinstance(rep, int)
        or rep < 0
    ):
        print(f"family={fam}: FAILED (unsafe_scenario_reference)")
        any_fail = True
        continue
    scenario_dir = os.path.join(retention_root, "scenarios", scenario_id, str(rep))
    if not within_retention_root(scenario_dir):
        print(f"family={fam}: FAILED (unsafe_scenario_reference)")
        any_fail = True
        continue
    recorded_digests = entry.get("inspected_artifact_digests") or {}
    # Advisor review of T-E40-F10-006's rework (this file's own comment on
    # digest_of_path already names the failure mode): a recorded digest that
    # is missing or not a non-empty string -- a forged/hand-edited row, or a
    # pre-fix --record that never wrote a key for an artifact -- makes
    # `current != recorded_digests.get(name)` compare None == None when the
    # artifact is ALSO currently missing on disk, which is not a staleness
    # mismatch and would wrongly report "verified" with zero digests
    # actually inspected. Every recorded digest must be a real non-empty
    # string BEFORE the staleness comparison runs, so None can never match
    # None.
    incomplete = [
        name
        for name in RETAINED_ARTIFACTS
        if not isinstance(recorded_digests.get(name), str) or not recorded_digests[name]
    ]
    if incomplete:
        print(f"family={fam}: FAILED (incomplete_attestation: {', '.join(incomplete)})")
        any_fail = True
        continue
    stale = []
    for name in RETAINED_ARTIFACTS:
        current = digest_of_path(os.path.join(scenario_dir, name))
        if current != recorded_digests.get(name):
            stale.append(name)
    if stale:
        print(f"family={fam}: FAILED (stale_digest: {', '.join(stale)})")
        any_fail = True
    else:
        print(f"family={fam}: verified")

if not targets:
    print("pilot-ledger: no attestations recorded", file=sys.stderr)

raise SystemExit(1 if any_fail else 0)
PYEOF
	exit $?
	;;
esac
