#!/usr/bin/env bash
# pilot-ledger.sh --retention-root <retention_root> --record --scenario <id>
#                  --rep <n> --operator <identity> --checklist <checklist.json>
# pilot-ledger.sh --retention-root <retention_root> --verify [--family <f>]
#
# T-E40-F10-006 (spec.md REQ-F-005, ADR-F10-09): the offline pilot-inspection
# attestation ledger. `--record` appends one operator attestation per
# scenario family into <retention_root>/pilot-ledger.jsonl, capturing the
# inspected run reference, the checklist item results, the inspecting
# operator identity, and the digests of the retained artifacts inspected.
# `--verify` re-computes those same digests from the artifacts CURRENTLY
# retained on disk and reports per-family pass/fail.
#
# ADR-F10-09: the gate is an artifact-digest attestation, not a boolean
# flag or a bare run-id reference -- either of those would be unable to
# detect a later change to the retained evidence. `--verify` therefore
# never trusts a stored digest without recomputing it fresh.
#
# Digest computation (bench/reports/lifecycle-baseline-schema.yaml
# digest_rules, matching I-05/I-07/I-08's own digest_rules blocks):
# algorithm sha256, lowercase hex encoding. A single file is digested as
# `file_encoding: sha256_raw_bytes` (raw bytes, no re-serialization). A
# directory (evidence/, transcripts/) is digested as a `canonicalization:
# compact_json_sorted_keys_utf8` document: the sorted list of
# {relative_path, sha256_raw_bytes} for every file it contains, sha256'd.
#
# The eight artifacts digested per (scenario, rep) are exactly
# bench/reports/lifecycle-baseline-schema.yaml's `retention_required_
# artifacts` list (spec.md Data model changes): package.yaml, evidence,
# transcripts, entity-history.json, lifecycle.jsonl, evaluation.jsonl,
# oracle.json, manifest.json.
#
# Ledger row fields match the schema's `pilot_attestation_required_fields`:
# /run_reference, /checklist_results, /operator_identity,
# /inspected_artifact_digests (plus this script's own `family` and
# `recorded_at` bookkeeping fields, which the schema does not forbid).
#
# `--verify` groups the (append-only) ledger by family and uses the LATEST
# row recorded for each family -- a re-attestation supersedes an earlier
# one, it does not need to be deleted. Verifying a family absent from the
# ledger fails with `no_attestation`; verifying a family whose recorded
# digests no longer match the current retained bytes fails with
# `stale_digest` (naming the artifact(s) that changed) -- this is also
# what catches a `--reclaim-incomplete`-quarantined-and-rerun pair: the
# regenerated bytes at the same retention path simply recompute to a
# different digest, with no special-case code required.
#
# Exit status: 0 record success / verify all-requested-families pass,
# 1 verify found at least one failing family, 2 usage error.
set -euo pipefail

usage() {
	cat >&2 <<'EOF'
usage: pilot-ledger.sh --retention-root <retention_root> --record \
         --scenario <id> --rep <n> --operator <identity> \
         --checklist <checklist.json>
       pilot-ledger.sh --retention-root <retention_root> --verify [--family <f>]
EOF
	exit 2
}

retention_root=""
action=""
scenario=""
rep=""
operator=""
checklist=""
family=""

while [[ $# -gt 0 ]]; do
	case "$1" in
	--retention-root)
		[[ $# -ge 2 ]] || usage
		retention_root="$2"
		shift 2
		;;
	--record)
		[[ -z "$action" ]] || usage
		action="record"
		shift
		;;
	--verify)
		[[ -z "$action" ]] || usage
		action="verify"
		shift
		;;
	--scenario)
		[[ $# -ge 2 ]] || usage
		scenario="$2"
		shift 2
		;;
	--rep)
		[[ $# -ge 2 ]] || usage
		rep="$2"
		shift 2
		;;
	--operator)
		[[ $# -ge 2 ]] || usage
		operator="$2"
		shift 2
		;;
	--checklist)
		[[ $# -ge 2 ]] || usage
		checklist="$2"
		shift 2
		;;
	--family)
		[[ $# -ge 2 ]] || usage
		family="$2"
		shift 2
		;;
	--help)
		usage
		;;
	*)
		usage
		;;
	esac
done

[[ -n "$retention_root" ]] || usage
[[ -n "$action" ]] || usage

command -v python3 >/dev/null 2>&1 || {
	echo "pilot-ledger: python3 not found on PATH" >&2
	exit 2
}

[[ -d "$retention_root" ]] || {
	echo "pilot-ledger: retention root not found: $retention_root" >&2
	exit 2
}
RETENTION_ROOT_CANON="$(cd "$retention_root" && pwd)"
LEDGER_PATH="$RETENTION_ROOT_CANON/pilot-ledger.jsonl"

case "$action" in
record)
	[[ -n "$scenario" ]] || usage
	[[ -n "$rep" ]] || usage
	[[ "$rep" =~ ^[0-9]+$ ]] || {
		echo "pilot-ledger: --rep must be a non-negative integer, got '$rep'" >&2
		exit 2
	}
	[[ -n "$operator" ]] || usage
	[[ -n "$checklist" ]] || usage
	[[ -f "$checklist" ]] || {
		echo "pilot-ledger: checklist file not found: $checklist" >&2
		exit 2
	}

	python3 - "$RETENTION_ROOT_CANON" "$scenario" "$rep" "$operator" "$checklist" "$LEDGER_PATH" <<'PYEOF'
import hashlib
import json
import os
import sys
import time

try:
    import yaml
except ImportError:
    print("pilot-ledger: PyYAML not available", file=sys.stderr)
    raise SystemExit(2)

retention_root, scenario_id, rep_str, operator, checklist_path, ledger_path = sys.argv[1:7]
rep = int(rep_str)

# The eight canonical retained artifacts (bench/reports/
# lifecycle-baseline-schema.yaml retention_required_artifacts).
RETAINED_ARTIFACTS = [
    "package.yaml", "evidence", "transcripts", "entity-history.json",
    "lifecycle.jsonl", "evaluation.jsonl", "oracle.json", "manifest.json",
]


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def digest_of_path(path):
    # file_encoding: sha256_raw_bytes for a single file; a directory is
    # digested as canonicalization: compact_json_sorted_keys_utf8 over the
    # sorted {path, sha256} list of every file it contains -- both under
    # the shared digest_rules algorithm/encoding (sha256, lowercase hex).
    if os.path.isdir(path):
        entries = []
        for root, dirs, files in os.walk(path):
            dirs.sort()
            for fname in sorted(files):
                fpath = os.path.join(root, fname)
                relpath = os.path.relpath(fpath, path).replace(os.sep, "/")
                with open(fpath, "rb") as fh:
                    entries.append({"path": relpath, "sha256": sha256_bytes(fh.read())})
        entries.sort(key=lambda e: e["path"])
        canonical = json.dumps(entries, sort_keys=True, separators=(",", ":")).encode("utf-8")
        return sha256_bytes(canonical)
    if os.path.isfile(path):
        with open(path, "rb") as fh:
            return sha256_bytes(fh.read())
    return None


scenario_dir = os.path.join(retention_root, "scenarios", scenario_id, str(rep))
if not os.path.isdir(scenario_dir):
    print(f"pilot-ledger: no retained scenario directory found: {scenario_dir}", file=sys.stderr)
    raise SystemExit(2)

package_path = os.path.join(scenario_dir, "package.yaml")
if not os.path.isfile(package_path):
    print(f"pilot-ledger: package.yaml missing under {scenario_dir}", file=sys.stderr)
    raise SystemExit(2)
with open(package_path) as f:
    pkg = yaml.safe_load(f) or {}
family = str(pkg.get("entity_family") or "")
if not family:
    print(f"pilot-ledger: {package_path} has no entity_family; cannot determine scenario family", file=sys.stderr)
    raise SystemExit(2)

digests = {}
missing = []
for name in RETAINED_ARTIFACTS:
    digest = digest_of_path(os.path.join(scenario_dir, name))
    if digest is None:
        missing.append(name)
    digests[name] = digest
if missing:
    print(
        f"pilot-ledger: cannot record attestation, missing retained artifact(s) under {scenario_dir}: {', '.join(missing)}",
        file=sys.stderr,
    )
    raise SystemExit(2)

with open(checklist_path) as f:
    checklist_results = json.load(f)

record = {
    "family": family,
    "run_reference": {
        "scenario_id": scenario_id,
        "rep": rep,
        "retention_path": f"scenarios/{scenario_id}/{rep}",
    },
    "operator_identity": operator,
    "checklist_results": checklist_results,
    "inspected_artifact_digests": digests,
    "recorded_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
}
with open(ledger_path, "a", encoding="utf-8") as f:
    f.write(json.dumps(record, sort_keys=True) + "\n")

print(f"pilot-ledger: recorded attestation for family '{family}' (scenario_id={scenario_id}, rep={rep})")
PYEOF
	exit $?
	;;
verify)
	python3 - "$RETENTION_ROOT_CANON" "$LEDGER_PATH" "$family" <<'PYEOF'
import hashlib
import json
import os
import sys

retention_root, ledger_path, family_filter = sys.argv[1:4]

RETAINED_ARTIFACTS = [
    "package.yaml", "evidence", "transcripts", "entity-history.json",
    "lifecycle.jsonl", "evaluation.jsonl", "oracle.json", "manifest.json",
]


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def digest_of_path(path):
    if os.path.isdir(path):
        entries = []
        for root, dirs, files in os.walk(path):
            dirs.sort()
            for fname in sorted(files):
                fpath = os.path.join(root, fname)
                relpath = os.path.relpath(fpath, path).replace(os.sep, "/")
                with open(fpath, "rb") as fh:
                    entries.append({"path": relpath, "sha256": sha256_bytes(fh.read())})
        entries.sort(key=lambda e: e["path"])
        canonical = json.dumps(entries, sort_keys=True, separators=(",", ":")).encode("utf-8")
        return sha256_bytes(canonical)
    if os.path.isfile(path):
        with open(path, "rb") as fh:
            return sha256_bytes(fh.read())
    return None


# Group by family; an append-only ledger's LATEST row per family is the
# current attestation -- a re-record supersedes an earlier one.
latest_by_family = {}
if os.path.isfile(ledger_path):
    with open(ledger_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                continue
            fam = entry.get("family")
            if fam:
                latest_by_family[fam] = entry

targets = [family_filter] if family_filter else sorted(latest_by_family.keys())

any_fail = False
for fam in targets:
    entry = latest_by_family.get(fam)
    if entry is None:
        print(f"family={fam}: FAILED (no_attestation)")
        any_fail = True
        continue
    ref = entry.get("run_reference") or {}
    scenario_id = ref.get("scenario_id")
    rep = ref.get("rep")
    scenario_dir = os.path.join(retention_root, "scenarios", str(scenario_id), str(rep))
    recorded_digests = entry.get("inspected_artifact_digests") or {}
    stale = []
    for name in RETAINED_ARTIFACTS:
        current = digest_of_path(os.path.join(scenario_dir, name))
        if current != recorded_digests.get(name):
            stale.append(name)
    if stale:
        print(f"family={fam}: FAILED (stale_digest: {', '.join(stale)})")
        any_fail = True
    else:
        print(f"family={fam}: verified")

if not targets:
    print("pilot-ledger: no attestations recorded", file=sys.stderr)

raise SystemExit(1 if any_fail else 0)
PYEOF
	exit $?
	;;
esac
